apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-deployment
  labels:
    app: devops-dashboard
spec:
  # SCALING: Run 2 replicas to ensure high availability
  replicas: 2
  selector:
    matchLabels:
      app: devops-dashboard
  template:
    metadata:
      labels:
        app: devops-dashboard
    spec:
      containers:
        - name: dashboard-container
          image: devops-dashboard:v1
          # IMPORTANT for local K8s: Use local image instead of trying to pull from internet
          imagePullPolicy: Never
          ports:
            - containerPort: 80

          # RESOURCES: Limit memory/cpu usage
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

          # SELF-HEALING: K8s checks if app is alive. If not, it restarts the pod.
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
