apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
spec:
  # Expose service externally (Localhost/Cloud IP)
  type: LoadBalancer
  selector:
    # Traffic routing target
    app: devops-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
