apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
spec:
  # TRAFFIC DISTRIBUTION: LoadBalancer distributes traffic across all replicas
  type: LoadBalancer
  selector:
    app: devops-dashboard
  ports:
    - protocol: TCP
      port: 80 # Port exposed to the cluster/world
      targetPort: 80 # Port inside the container
